version: '3.8'

services:
  regador-api:
    container_name: regador_api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home/app:delegated
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/regadorDB
      SPRING_DATASOURCE_USERNAME: microuser
      SPRING_DATASOURCE_PASSWORD: secret
    depends_on:
      - postgres


  postgres:
    container_name: regador_postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: regadorDB
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: microuser
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
